project:
  type: website
  output-dir: docs
  
website:
    title: "Prácticas Lógica Matemática: PROLOG"
    page-footer: 
      background: light
      left: 2025 Carviagu. Powered with [Quarto](https://quarto.org/) and [GitHub](https://pages.github.com/)
      right: |
        [![](resources/images/logo2.png){fig-alt="CUNEF" width=65px}](https://cunef.edu)
        
    navbar:
      search: false
      background: light
      title: false
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true